export const tableData = [
  {
    id: 1,
    first_name: "Ellerey",
    last_name: "Scaife",
    email: "escaife0@ihg.com",
    gender: "Male",
    ip_address: "246.166.226.123",
  },
  {
    id: 2,
    first_name: "Dilly",
    last_name: "Newell",
    email: "dnewell1@bluehost.com",
    gender: "Male",
    ip_address: "124.228.153.23",
  },
  {
    id: 3,
    first_name: "Carlotta",
    last_name: "Bausmann",
    email: "cbausmann2@tinypic.com",
    gender: "Bigender",
    ip_address: "117.169.70.35",
  },
  {
    id: 4,
    first_name: "Jacki",
    last_name: "Kunneke",
    email: "jkunneke3@ask.com",
    gender: "Female",
    ip_address: "20.66.152.198",
  },
  {
    id: 5,
    first_name: "Tim",
    last_name: "Serfati",
    email: "tserfati4@amazonaws.com",
    gender: "Female",
    ip_address: "72.93.181.100",
  },
  {
    id: 6,
    first_name: "Aloin",
    last_name: "Bruggen",
    email: "abruggen5@jimdo.com",
    gender: "Male",
    ip_address: "48.18.44.16",
  },
  {
    id: 7,
    first_name: "Bryce",
    last_name: "Ardley",
    email: "bardley6@typepad.com",
    gender: "Male",
    ip_address: "62.117.198.24",
  },
  {
    id: 8,
    first_name: "Alice",
    last_name: "Gaither",
    email: "agaither7@zdnet.com",
    gender: "Female",
    ip_address: "65.49.108.41",
  },
  {
    id: 9,
    first_name: "Freda",
    last_name: "Lissandri",
    email: "flissandri8@washingtonpost.com",
    gender: "Female",
    ip_address: "217.49.90.53",
  },
  {
    id: 10,
    first_name: "Gustavus",
    last_name: "Moxon",
    email: "gmoxon9@archive.org",
    gender: "Male",
    ip_address: "218.146.219.125",
  },
];
